/* =========================================================
   merge.js — Combine all questions-*-all.js into one questions.js
   ========================================================= */

const fs = require("fs");
const path = require("path");

const jsDir = "js";
const outFile = path.join(jsDir, "questions.js");

// Find all questions-*-all.js files (our generated ones)
const files = fs.readdirSync(jsDir)
    .filter(f => /^questions-.*-all\.js$/.test(f));

if (!files.length) {
    console.error("No questions-*-all.js files found in js/");
    process.exit(1);
}

let all = [];
let perFile = [];

files.forEach(file => {
    const content = fs.readFileSync(path.join(jsDir, file), "utf-8");
    // Extract the array literal after "const questionBank = "
    const match = content.match(/const questionBank\s*=\s*(\[[\s\S]*\]);?\s*$/);
    if (!match) {
        console.log("SKIP (no bank): " + file);
        return;
    }
    try {
        const arr = eval(match[1]);
        if (Array.isArray(arr) && arr.length > 0) {
            perFile.push({ file, count: arr.length });
            all = all.concat(arr);
        } else {
            console.log("SKIP (empty): " + file);
        }
    } catch (e) {
        console.log("SKIP (parse error): " + file + " — " + e.message);
    }
});

// Re-number IDs sequentially
all.forEach((q, i) => { q.id = i + 1; });

const output =
    "/* =========================================================\n" +
    "   Master Question Bank — auto-generated by merge.js\n" +
    "   Generated: " + new Date().toISOString() + "\n" +
    "   Total questions: " + all.length + "\n" +
    "   ========================================================= */\n\n" +
    "const questionBank = " + JSON.stringify(all, null, 2) + ";\n";

fs.writeFileSync(outFile, output, "utf-8");

console.log("");
console.log("Merged files:");
perFile.forEach(p => console.log("  " + p.file + " → " + p.count + " questions"));
console.log("");
console.log("TOTAL: " + all.length + " questions");
console.log("Saved to: " + outFile);